name: Main CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint pytest-cov

    - name: Discover and process projects
      run: |
        for project in $(find . -type d -name 'tests' -exec dirname {} \; | sort -u); do
          echo "Processing project: $project"
          
          if [ -d "$project/source" ]; then
            # Extract the base folder name (e.g., 'basic_functions' from './basic_functions')
            base=$(basename "$project")
            echo "Running pylint for $project/$base"
            pylint "$project/$base" || true
          fi
          
          if [ -d "$project/tests" ]; then
            echo "Running tests for $project"
            cd "$project"
            pytest --cov=source
            cd - > /dev/null
          fi
        done

